config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes do
    resources :line_item_dates, except: [ :index, :show ] do
      resources :line_items, except: [ :index, :show ]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates

  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  broadcasts_to ->(quote) { [ quote.company, "quotes" ] }, inserts_by: :prepend

  def total_price
    line_items.sum(&:total_price)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = current_company.quotes.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = current_company.quotes.build(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_path, status: :see_other, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = current_company.quotes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.expect(quote: [ :name ])
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_empty_state.html.slim
.empty-state.empty-state--only-child
  p.empty-state__text You don't have any quotes yet!

  = link_to "Add quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Quote.new) }

app/views/quotes/_form.html.slim
= form_with(model: quote) do |form|
  = form_error_notification(quote)
  
  .quote
    div
      = form.label :name, style: "display: block"
      = form.text_field :name
    div
      = form.submit class: "btn btn--primary"
      = link_to "Cancel", quotes_path, class: "btn"

app/views/quotes/_quote.html.slim
= turbo_frame_tag quote do
  div.quote id="#{dom_id quote}"
    = link_to quote.name, quote, data: { turbo_frame: "_top" }, class: "quote__title"
    .quote__actions
      = link_to "Edit", edit_quote_path(quote), class: "btn"
      = button_to "Delete", quote, method: :delete, class: "btn btn--destructive"

app/views/quotes/_total.html.slim
footer.quote-total 
  .quote-total__inner.container
    span Total:
    span = number_to_currency quote.total_price

app/views/quotes/create.turbo_stream.slim
= turbo_stream.prepend "quotes", @quote
= turbo_stream.update Quote.new, ""
= render_turbo_stream_flash_messages

app/views/quotes/destroy.turbo_stream.slim
= turbo_stream.remove "quote_#{@quote.id}"
= render_turbo_stream_flash_messages

app/views/quotes/edit.html.slim
h1 Edit quote

= turbo_frame_tag @quote do
  == render "form", quote: @quote

br

div
  => link_to "Show this quote", @quote
  '|
  =< link_to "Back to quotes", quotes_path

app/views/quotes/index.html.slim
= turbo_stream_from current_company, "quotes"

.homepage
  .homepage__header
    h1 Quotes
    = link_to "New quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Quote.new) }

  = turbo_frame_tag Quote.new

  = turbo_frame_tag "quotes", class: "quotes" do
    = render 'quotes/empty_state'
    == render @quotes

app/views/quotes/new.html.slim
h1 New quote

= turbo_frame_tag @quote do
  == render "form", quote: @quote

br

div
  = link_to "Back to quotes", quotes_path

app/views/quotes/show.html.slim
main.container.container--quote
  = link_to "Back to quotes", quotes_path
  .header 
    h1 = @quote.name
    = link_to "New date", new_quote_line_item_date_path(@quote), data: { turbo_frame: dom_id(LineItemDate.new) }, class: "btn btn--primary"
  
  = turbo_frame_tag LineItemDate.new

  = turbo_frame_tag "line_item_dates" do
    .dates
      = render @line_item_dates, quote: @quote

= turbo_frame_tag dom_id(@quote, :total) do
  = render "quotes/total", quote: @quote

app/views/quotes/update.turbo_stream.slim
= turbo_stream.replace @quote
= render_turbo_stream_flash_messages